package constants

const (
	ERROR                                 = "ERROR"
	READY                                 = "READY"
	VOICE_STATE_UPDATE                    = "VOICE_STATE_UPDATE"
	SPEAKING_START                        = "SPEAKING_START"
	SPEAKING_STOP                         = "SPEAKING_STOP"
	ACTIVITY_LAYOUT_MODE_UPDATE           = "ACTIVITY_LAYOUT_MODE_UPDATE"
	ORIENTATION_UPDATE                    = "ORIENTATION_UPDATE"
	CURRENT_USER_UPDATE                   = "CURRENT_USER_UPDATE"
	ENTITLEMENT_CREATE                    = "ENTITLEMENT_CREATE"
	THERMAL_STATE_UPDATE                  = "THERMAL_STATE_UPDATE"
	ACTIVITY_INSTANCE_PARTICIPANTS_UPDATE = "ACTIVITY_INSTANCE_PARTICIPANTS_UPDATE"
)

var Events = []string{
	READY,
	VOICE_STATE_UPDATE,
	SPEAKING_START,
	SPEAKING_STOP,
	ACTIVITY_LAYOUT_MODE_UPDATE,
	ORIENTATION_UPDATE,
	CURRENT_USER_UPDATE,
	ENTITLEMENT_CREATE,
	THERMAL_STATE_UPDATE,
	ACTIVITY_INSTANCE_PARTICIPANTS_UPDATE,
}
